# -*- coding: utf-8 -*-
"""CSE5544.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LczhbLJpFaqX_1DfFbtKWasIVw36-1GZ
"""

import pandas as pd

df= pd.read_csv("coffee_survey.csv")

df.head(10)

df.describe()

df.info()

df['total_spend']

df['total_spend']

df.info()

df.head()

df.dropna(subset=['total_spend'], inplace=True)
df['total_spend']

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.hist(df['total_spend'], bins=20, edgecolor='black')
plt.xlabel('Total Spend')
plt.ylabel('Frequency')
plt.title('Money Spent in a month')
plt.show()

# grouped_by_age = df.groupby('age')['total_spend'].mean()
# grouped_by_age

# df_cleaned = df.dropna(subset=['total_spend'])

# # Define bins and labels for spend range bins = [20, 40, 60, 80, 100, float('inf')]
# labels = ['20-40', '40-60', '60-80', '80-100']
# bins = [20, 40, 60, 80, float('inf')]

# # Create a new column categorizing each spend into these ranges
# df_cleaned['spend_range'] = pd.cut(df_cleaned['total_spend'], bins=bins, labels=labels, right=False)
# grouped_spent_equipment = df.groupby(['age', 'spent_equipment']).size().unstack(fill_value=0)

# # Count frequency of each spend range
# spend_range_counts = df_cleaned['spend_range'].value_counts().sort_index()

# spend_range_counts

grouped_spent_equipment = df.groupby(['age', 'total_spend']).size().unstack(fill_value=0)
grouped_spent_equipment

#percentage
grouped_spent_equipment = df.groupby(['age', 'total_spend']).size().unstack(fill_value=0)

grouped_spent_equipment_percentage = grouped_spent_equipment.div(grouped_spent_equipment.sum(axis=1), axis=0) * 100

grouped_spent_equipment_percentage

#graph

import matplotlib.pyplot as plt

grouped_spent_equipment_percentage.plot(kind='bar', figsize=(10, 6))
plt.xlabel('Age')
plt.ylabel('Percentage')
plt.title('Percentage of Total Spend by Age and Equipment')
plt.legend(title='Total Spend')
plt.show()

grouped_spent_equipment_g = df.groupby(['gender', 'total_spend']).size().unstack(fill_value=0)
grouped_spent_equipment_g

grouped_spent_equipment_percentage_g = grouped_spent_equipment_g.div(grouped_spent_equipment_g.sum(axis=1), axis=0) * 100

grouped_spent_equipment_percentage_g

grouped_spent_equipment_percentage_g.plot(kind='bar', figsize=(10, 6))
plt.xlabel('gender')
plt.ylabel('Percentage')
plt.title('Percentage of Total Spend by gender and Equipment')
plt.legend(title='Total Spend')
plt.show()

df["most_paid"]

grouped_spent_equipment_e = df.groupby(['ethnicity_race', 'total_spend']).size().unstack(fill_value=0)
grouped_spent_equipment_e

grouped_spent_equipment_percentage_e= grouped_spent_equipment_e.div(grouped_spent_equipment_e.sum(axis=1), axis=0) * 100

grouped_spent_equipment_percentage_e

grouped_spent_equipment_ed = df.groupby(['education_level', 'total_spend']).size().unstack(fill_value=0)
grouped_spent_equipment_ed

grouped_spent_equipment_percentage_ed= grouped_spent_equipment_ed.div(grouped_spent_equipment_ed.sum(axis=1), axis=0) * 100

grouped_spent_equipment_percentage_ed

grouped_spent_equipment_percentage_ed.plot(kind='bar', figsize=(10, 6))
plt.xlabel('education_level')
plt.ylabel('Percentage')
plt.title('Percentage of Total Spend by education and Equipment')
plt.legend(title='Total Spend')
plt.show()

grouped_most_willing_age = df.groupby(['age', 'most_willing']).size().unstack(fill_value=0)
grouped_most_willing_age

grouped_spent_equipment_percentage_age= grouped_most_willing_age.div(grouped_most_willing_age.sum(axis=1), axis=0) * 100

grouped_spent_equipment_percentage_age

grouped_spent_equipment_percentage_age.plot(kind='line', figsize=(10, 6))
plt.xlabel('education_level')
plt.ylabel('Percentage')
plt.title('Percentage of Total Spend by education and Equipment')
plt.legend(title='Total Spend')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 8))
sns.heatmap(grouped_spent_equipment_percentage_age, annot=True, fmt=".1f")
plt.title("Heatmap of Percentage of Total Spend by Age and Most Willing")
plt.xlabel("Most Willing")
plt.ylabel("Age")
plt.show()

grouped_spent_equipment_po = df.groupby(['number_children', 'most_willing']).size().unstack(fill_value=0)
grouped_spent_equipment_po

